# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.
---
apiVersion: v1
kind: Secret
metadata:
    name: afc_secrets
stringData:
    OIDC.json: |
        {
            "LOGIN": null,
            "CLIENT_ID": null,
            "CLIENT_SECRET": null,
            "DISCOVERY_URL": null
        }

    REGISTRATION_CAPTCHA.json: |
        {
            "USE_CAPTCHA": null,
            "SECRET": null,
            "SITEKEY": null,
            "VERIFY": null
        }

    NOTIFIER_MAIL.json: |
        {
            "SERVER": null,
            "PORT": null,
            "USE_TLS": null,
            "USE_SSL": null,
            "USERNAME": null,
            "PASSWORD": null
        }

    REGISTRATION.json: |
        {
            "DEST_EMAIL": null,
            "DEST_PDL_EMAIL": null,
            "SRC_EMAIL": null,
            "APPROVE_LINK": null,
        }
