# Default values for afc-int.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  msqhnd: 1
  objst: 1
  rmq: 1
  worker: 10
  webui: 1

image:
  msghnd:
    #repository: 110738915961.dkr.ecr.us-east-1.amazonaws.com/afc-msghnd
    repository: wcc-afc-docker-virtual.usw2.packages.broadcom.com/afc-msghnd
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    #tag: "3.8.2.0"
  webui:
    #repository: 110738915961.dkr.ecr.us-east-1.amazonaws.com/afc-server
    repository: wcc-afc-docker-virtual.usw2.packages.broadcom.com/afc-server
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    #tag: "3.8.2.0"
  objst:
    repository: public.ecr.aws/w9v6y1o0/openafc/objstorage-image
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    #tag: "3.8.2.0"
  worker:
    #repository: 110738915961.dkr.ecr.us-east-1.amazonaws.com/afc-worker
    repository: wcc-afc-docker-virtual.usw2.packages.broadcom.com/afc-worker
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    #tag: "3.8.2.0"
  rmq:
    repository: public.ecr.aws/w9v6y1o0/openafc/rmq-image
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    #tag: "3.8.2.0"


imagePullSecrets: []
nameOverride: "afc-app"
#fullnameOverride: "afc-chart"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  msghnd:
    type: LoadBalancer
    port: 80
    containerPort: 8000
    loadBalancerIP: 10.255.128.212
  webui:
    type: LoadBalancer
    port: 80
    loadBalancerIP: 10.255.128.213
  rmq:
    type: LoadBalancer
    port: 5672
    loadBalancerIP: 10.255.128.214
  objst:
    type: LoadBalancer
    fileStoragePort: 5000
    historyViewPort: 4999
    loadBalancerIP: 10.255.128.215
  kafka:
    type: LoadBalancer
    port: 9092
    loadBalancerIP: 10.255.128.216


ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
