# Copyright (C) 2021 Broadcom. All rights reserved. The term "Broadcom"
# refers solely to the Broadcom Inc. corporate affiliate that owns
# the software below. This work is licensed under the OpenAFC Project License,
# a copy of which is included with this software program
#

# ALS JSON logs data source
---
apiVersion: 1

{% if GRAFANA_DS_JSON_LOG_RO_DSN is defined -%}
deleteDatasources:
  - name: AlsJson

datasources:
  - access: proxy
    apiVersion: ''
    basicAuth: false
    basicAuthUser: ''
    database: ''
    isDefault: false
    jsonData:
      connMaxLifetime: 14400
      database: >-
        {{ GRAFANA_DS_JSON_LOG_RO_DSN | dsn_parse("path") | trim("/") }}
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      postgresVersion: 1400
      {%- set scheme %}{{ GRAFANA_DS_JSON_LOG_RO_DSN | dsn_parse("scheme") }}{% endset %}
      sslmode: >-
        {{ "require" if scheme == "https" else "disable" }}
    name: AlsJson
    orgId: 1
    readOnly: true
    secureJsonFields:
      password: >-
        {% if GRAFANA_DS_JSON_LOG_RO_PASSWORD_FILE is defined %}$__file{ {{- GRAFANA_DS_JSON_LOG_RO_PASSWORD_FILE -}} }{% else %}{{ GRAFANA_DS_JSON_LOG_RO_DSN | dsn_parse("password") | default("") }}{% endif %}
    type: grafana-postgresql-datasource
    typeLogoUrl: public/app/plugins/datasource/grafana-postgresql-datasource/img/postgresql_logo.svg
    url: >-
      {{ GRAFANA_DS_JSON_LOG_RO_DSN | dsn_parse("hostname") }}:{{ GRAFANA_DS_JSON_LOG_RO_DSN | dsn_parse("port") | default("5432", True) }}
    user: >-
      {{ GRAFANA_DS_JSON_LOG_RO_DSN | dsn_parse("username") }}
    version: 4
    withCredentials: false
{% endif %}
