# Service Account for Prometheus. End goal is for Prometheus to be able to list
# Services and Pods on API Server)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
  # annotations:
  #   eks.amazonaws.com/role-arn: "arn:aws:iam::<acc-id>:role/prometheus"
