# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:          # List of stages for jobs, and their order of execution
  - merge_upstream
  - getsrc
  - build
  - test
  - deploy_stg
  - deploy_prd

# This jobs checks for changes in upstream and pushes new changes if found.
# It's running on schedule every 30 minutes.
merge_upstream_changes:
  stage: merge_upstream
  rules:
    - if: '($CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_NAME == "main")'
      when: always
  before_script:
  - git remote set-url origin https://git:${CI_PUSH_TOKEN}@wcc-gitlab.lvn.broadcom.net:30443/afc/brcm-afc.git
  - git config --global user.email "gitlab-runner@broadcom.com"
  - git config --global user.name "gitlab-runner"
  script:
    - git remote add upstream $CI_GITHUB_UPSTREAM  || true
    - git fetch upstream
    # # Ensure the local main branch exists and tracks origin/main
    - git fetch origin main
    - git checkout -B main origin/main
    - git reset --hard origin/main
    # Merge changes from upstream/main into the local main branch
    - UPSTREAM_CHANGES=$(git log HEAD..upstream/main --oneline)
    - |
      if [ -n "$UPSTREAM_CHANGES" ]; then
        git merge upstream/main
        # Push the changes back to origin/main
        git push origin main
      else
        echo "No changes found in the upstream repository."
      fi

# This job runs to create dir with unique name
# that includes sources that will be validated
getsrc_job:
  stage: getsrc
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule" && ($CI_COMMIT_REF_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")
      when: always
  script:
    - echo "create random number"
    - RAND=`date +"D_%d_%m_%y_T_%H_%M_%S_TZ_%Z"`_hash_`git rev-parse --short HEAD` && echo ${RAND}
    - echo "RAND=${RAND}" >> $CI_PROJECT_DIR/vars.env

    - echo "generate workdir which includes random number"
    - WD=$CI_WORKING_DIR/wccafc-dev_${RAND}
    - echo "WD=${WD}" >> $CI_PROJECT_DIR/vars.env

    - echo "rsync sources"
    - echo "cmd rsync -raz --delete ./ ${WD}"
    - rsync -raz --delete ./ ${WD}/
  artifacts:
    reports:
      dotenv: $CI_PROJECT_DIR/vars.env

# Building regression test images
build_job:
  stage: build
  needs:
    - getsrc_job
  rules:
    - if: '($CI_PIPELINE_SOURCE != "schedule" && ($CI_COMMIT_REF_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"))'
      when: always
  before_script:
    - if [ "$PUSH_DI" = "1" ]; then echo $ARTIFACTORY_PASSWORD | docker login -u $ARTIFACTORY_USER --password-stdin $PRIV_REPO; fi
  script:
    ######## git clone sources ##############
    # main repo already cloned and copied to:
    # $CI_WORKING_DIR/wccafc-dev_$RAND
    # now need to init submodules
    - cd "${WD}"

    # generate  regression dir path
    - REGRD=tests/regression_${RAND}
    - REGRD_ORIG=tests/regression
    - echo "REGRD=${REGRD}" >> $CI_PROJECT_DIR/vars.env

    # create regression dir which includes rand
    # it is done the name of dir is used by docker-compose to create service name
    - cp -r "${WD}/${REGRD_ORIG}/." "${WD}/${REGRD}/"
    # build regr test images
    - bash "${WD}/${REGRD}/build_imgs.sh" ${WD} ${RAND} ${PUSH_DI}
  # after_script:
  #   - if [ "$PUSH_DI" = "1" ]; then docker logout $PRIV_REPO; fi
  artifacts:
    reports:
      dotenv: $CI_PROJECT_DIR/vars.env

#Running tests
test_job:
  stage: test
  needs:
    - build_job
    - getsrc_job
  rules:
    - if: '($CI_PIPELINE_SOURCE != "schedule" && ($CI_COMMIT_REF_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"))'
      when: always
  variables:
    RUN_FROM_RAND: 1
  before_script:
    # start dev srvr
    - bash "${WD}/${REGRD}/run_srvr.sh" ${WD} ${RAND} ${RUN_FROM_RAND}
  script:
    # get dev srvr port num
    - TEST_PORT=`cd ${WD}/${REGRD} && TAG=${RAND} docker-compose port dispatcher 80 |sed 's/.*://'`
    - TEST_PORT_HTTPS=`cd ${WD}/${REGRD} && TAG=${RAND} docker-compose port dispatcher 443 |sed 's/.*://'`

    # run tests
    - bash "${WD}/${REGRD}/run_tests.sh" ${WD} rtest:${RAND} $CI_HOST_HOSTNAME ${TEST_PORT} http

    # run ngnx-rat_server-rmq-worker path tests
    - bash "${WD}/${REGRD}/run_tests.sh" ${WD} rtest:${RAND} $CI_HOST_HOSTNAME ${TEST_PORT} http 8 "AFCS.SRS.1,AFCS.URS.1,AFCS.FSP.1,AFCS.IBP.1,AFCS.SIP.1,BRCM.EXT_FSP.1" "--webui"
  after_script:
    # stop dev srvr
    - bash "${WD}/${REGRD}/stop_srvr.sh" ${WD} ${RAND}

#Deployment to Staging
deploy_to_staging:
  stage: deploy_stg
  script:
    - echo "Deploying to staging environment..."
  rules:
    - when: manual
  environment:
    name: staging

#Deployment to Production
deploy_to_production:
  stage: deploy_prd
  script:
    - echo "Deploying to production environment..."
  rules:
    - when: manual
  environment:
    name: production

