# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

# vp890322 ----------------------------------------------------------------------------------------------------------------------------------------------------
# commenting until further configuration
# stages:
#   - build
#
# docker-build:
#   image: docker:24.0.5
#   # services:
#   #   - docker:19.03.12-dind
#   stage: build
#   script:
#     - docker info
#     # - docker build -t my-image-name:${CI_COMMIT_REF_SLUG} .
#     # - docker push my-image-name:${CI_COMMIT_REF_SLUG}
# end vp890322 ----------------------------------------------------------------------------------------------------------------------------------------------------


# stages:
# - test
# sast:
#   stage: test
# include:
# - template: Security/SAST.gitlab-ci.yml
# - template: Security/Secret-Detection.gitlab-ci.yml
# # container_scanning:
# #   variables:
# #     DOCKER_IMAGE: ...
# #     DOCKER_USER: ...
# #     DOCKER_PASSWORD: ...
# - template: Jobs/Container-Scanning.gitlab-ci.yml
