FROM centos:7.7.1908 as staging
RUN mkdir -p /tmp/pkgs/
COPY prereqs/repo/*.rpm /tmp/pkgs/

RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash -
RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
RUN rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg
RUN yum -y install epel-release
RUN yum -y install subversion yum-utils rpm-build python2-devel redhat-rpm-config rpmlint cmake3 \
    ninja-build gcc-c++ python-devel lcov doxygen graphviz minizip-devel gtest-devel \
    boost169-devel qt5-qtbase-devel armadillo-devel gdal-devel checkpolicy python2-gnupg pexpect \
    rpm-sign createrepo python-nose python-flask python-pyxdg python-prettytable \
    selinux-policy-devel selinux-policy-targeted /tmp/pkgs/iturp452* \
    yarn nodejs

RUN cd /tmp/pkgs/ && rpmbuild --rebuild python-wtforms-2.2.1-6.el7.src.rpm
RUN yum -y install /root/rpmbuild/RPMS/noarch/python2-wtforms-2.2.1-6.el7.noarch.rpm \
    python-cryptography python2-flask-sqlalchemy python-flask-script python-blinker \
    python2-bcrypt python2-flask-migrate python-jwt
RUN cd /tmp/pkgs/ && \
    yum -y install python2-jsmin-2.2.2-2.el7.noarch.rpm python-wsgidav-2.4.1-1.el7.noarch.rpm \
    python2-flask-mail-0.9.1-2.el7.noarch.rpm python2-flask-user-1.0.1.5-1.el7.noarch.rpm \
    python2-flask_jsonrpc-0.3.1-1.el7.noarch.rpm python-flask-wtf-0.14.2-7.el7.noarch.rpm
RUN yum -y clean all
RUN rm -rf /tmp/* /var/tmp/*
COPY prereqs/entry.sh /wd/

FROM centos:7.7.1908
COPY --from=staging / /

LABEL version="fbrat-build-env"
WORKDIR /wd
CMD ["sh", "-x", "entry.sh"]