#
# Copyright (C) 2023 Broadcom. All rights reserved. The term "Broadcom"
# refers solely to the Broadcom Inc. corporate affiliate that owns
# the software below. This work is licensed under the OpenAFC Project License,
# a copy of which is included with this software program
#

# This is an addendum to main docker-compose.yaml that adds node-exporter
# service (Prometheus data source for host compose runs on)
---
services:
  node_exporter:
    image: bitnami/node-exporter:1.6.1-debian-11-r78
    restart: always
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro,rslave
    dns_search: [.]
