#
# Copyright (C) 2021 Broadcom. All rights reserved. The term "Broadcom"
# refers solely to the Broadcom Inc. corporate affiliate that owns
# the software below. This work is licensed under the OpenAFC Project License,
# a copy of which is included with this software program
#

# Cadvisor dockerfile

# Registry migrated from gcr.io/cadvisor/cadvisor to ghcr.io/google/cadvisor in v0.53.0
# Note: ghcr.io tags omit the 'v' prefix
FROM ghcr.io/google/cadvisor:0.56.2@sha256:5534ae91cbf3428998d60428d107cfdd97272d80658534ac6e54d8ce3b0c4d72

# Housekeeping interval
ENV CADVISOR_HOUSEKEEPING_INTERVAL=5s

# Metrics - comma separated list of metric groups (see
# https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md for
# more details)
# disk,diskIO added to expose per-container filesystem and block-I/O metrics in Grafana
ENV CADVISOR_METRICS=cpu,memory,process,sched,network,disk,diskIO

# Additional arguments
ENV CADVISOR_ADDITIONAL_ARGS=

EXPOSE 8080

ENTRYPOINT /usr/bin/cadvisor \
    -logtostderr \
    -docker_only=true \
    -store_container_labels=false \
    -housekeeping_interval=$CADVISOR_HOUSEKEEPING_INTERVAL \
    -enable_metrics=$CADVISOR_METRICS \
    -enable_load_reader=false \
    $CADVISOR_ADDITIONAL_ARGS

HEALTHCHECK CMD \
    wget --quiet --tries=1 --spider http://localhost:8080/healthz || exit 1