#
# Copyright (C) 2021 Broadcom. All rights reserved. The term "Broadcom"
# refers solely to the Broadcom Inc. corporate affiliate that owns
# the software below. This work is licensed under the OpenAFC Project License,
# a copy of which is included with this software program
#

# Grafana dockerfile (for future expansion)

FROM grafana/grafana-oss:10.2.0-ubuntu

EXPOSE 3000/tcp
