apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.service.als_kafka.hostname }}
  labels:
    {{- include "afc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.als_kafka }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "afc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "afc.selectorLabels" . | nindent 8 }}
        afc: als-kafka
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "afc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.service.als_kafka.hostname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.als_kafka.repository }}:{{ .Values.image.als_kafka.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.als_kafka.pullPolicy }}
          ports:
            - name: als-kafka-port
              containerPort: {{ .Values.service.als_kafka.port | int }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /fbrat/www/index.html
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            - name: KAFKA_ADVERTISED_HOST
              value: {{ .Values.service.als_kafka.hostname | quote }}
            - name: KAFKA_CLIENT_PORT
              value: {{ .Values.service.als_kafka.port | quote }}
            - name: KAFKA_MAX_REQUEST_SIZE
              value: {{ .Values.service.als_kafka.max_request_size | quote | replace ":" "" }}
          resources:
            {{- toYaml .Values.resources.als_kafka | nindent 12 }}
      imagePullSecrets:
        - name: container-repo-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
