apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.service.rmq.hostname }}
  labels:
    {{- include "afc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.rmq }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "afc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "afc.selectorLabels" . | nindent 8 }}
        afc: rmq
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "afc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.service.rmq.hostname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image:  "{{ .Values.image.rmq.repository }}:{{ .Values.image.rmq.tag  | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.rmq.pullPolicy }}
          ports:
            - name: rmqp
              containerPort: {{ .Values.service.rmq.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: rmqp
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: rmqp
          resources:
            {{- toYaml .Values.resources.rmq | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
