apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.webui.hostname | quote }}
  labels:
    {{- include "afc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webui.type }}
  ports:
    - port: {{ .Values.service.webui.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "afc.selectorLabels" . | nindent 4 }}
    afc: webui
