apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.objst.hostname | quote }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
  labels:
    {{- include "afc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.objst.type }}
  ports:
    - port: {{ .Values.service.objst.fileStoragePort }}
      targetPort: afc-objst-port
      protocol: TCP
      name: afc-objst-port
    - port: {{ .Values.service.objst.historyViewPort }}
      targetPort: afc-objst-hist
      protocol: TCP
      name: afc-objst-hist
  selector:
    {{- include "afc.selectorLabels" . | nindent 4 }}
    afc: objst
