apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.msghnd.hostname | quote }}
  labels:
    {{- include "afc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.msghnd.type }}
  ports:
    - port:  {{ .Values.service.msghnd.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "afc.selectorLabels" . | nindent 4 }}
    afc: msghnd
