apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.als_kafka.hostname | quote }}
  labels:
    {{- include "afc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.als_kafka.type }}
  ports:
    - name: als-kafka-port
      port: {{ .Values.service.als_kafka.port }}
      protocol: TCP
      targetPort: als-kafka-port
  selector:
    {{- include "afc.selectorLabels" . | nindent 4 }}
    afc: als-kafka
