#
# Copyright (C) 2021 Broadcom. All rights reserved. The term "Broadcom"
# refers solely to the Broadcom Inc. corporate affiliate that owns
# the software below. This work is licensed under the OpenAFC Project License,
# a copy of which is included with this software program
#

FROM grafana/loki:3.6.10@sha256:f59e6aedfee6af2388d69962b178a35a23152573b4bf0937106746deb7146ec7

# Directory where Loki stores chunks, indices, etc. if filesystem store is used
ENV GRAFANA_LOKI_DATA_FILESYSTEM_DIRECTORY=/loki

# Log retention period. 0 to store forever
ENV GRAFANA_LOKI_RETENTION_PERIOD=10d

WORKDIR /wd

COPY loki-config.yaml /wd/

ENTRYPOINT ["loki", "-config.file=/wd/loki-config.yaml", "-config.expand-env"]
