#
# Copyright (C) 2021 Broadcom. All rights reserved. The term "Broadcom"
# refers solely to the Broadcom Inc. corporate affiliate that owns
# the software below. This work is licensed under the OpenAFC Project License,
# a copy of which is included with this software program
#

FROM grafana/loki:3.3.2

# Directory where Loki stores chunks, indices, etc. if filesystem store is used
ENV GRAFANA_LOKI_DATA_FILESYSTEM_DIRECTORY=/loki

# Log retention period. 0 to store forever
ENV GRAFANA_LOKI_RETENTION_PERIOD=10d

WORKDIR /wd

COPY loki-config.yaml /wd/

ENTRYPOINT loki -config.file=/wd/loki-config.yaml  -config.expand-env
