apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "afc-engine.fullname" . }}-worker
  labels:
    {{- include "afc-engine.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  #replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "afc-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "afc-engine.selectorLabels" . | nindent 8 }}
        afc: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "afc-engine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image:  110738915961.dkr.ecr.us-east-1.amazonaws.com/afc-worker:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: rmqp
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: rmqp
          volumeMounts:
            - mountPath: "/mnt/nfs"
              name: cont-confs
          env:
            # RabbitMQ server name:
            - name: BROKER_TYPE
              value: "external"
            - name: BROKER_FQDN
              value: {{ include "afc-engine.fullname" . }}-rmq
            # Filestorage params:
            - name: AFC_OBJST_HOST
              value: {{ include "afc-engine.fullname" . }}-objst
            - name: AFC_OBJST_PORT
              value: "5000"
            - name: AFC_OBJST_SCHEME
              value: "HTTP"
            # celery params
            - name: CELERY_OPTIONS
              value: "rat_worker"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cont-confs
          persistentVolumeClaim:
            claimName: cont-confs-claim
      imagePullSecrets:
        - name: ecr-docker-login
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
