apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: rb-ecr-renew
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ecr-renew
subjects:
  - kind: ServiceAccount
    name: svc-ecr-renew
    namespace: default