apiVersion: v1
kind: Service
metadata:
  name: afc
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
  labels:
    {{- include "afc-engine.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "afc-engine.selectorLabels" . | nindent 4 }}
    afc: apache
