apiVersion: v1
kind: Service
metadata:
  name: {{ include "afc-engine.fullname" . }}-worker
  labels:
    {{- include "afc-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "afc-engine.selectorLabels" . | nindent 4 }}
    afc: worker
