apiVersion: v1
kind: Service
metadata:
  name: ratdb
  labels:
    {{- include "afc-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: psql
      protocol: TCP
      name: psql
  selector:
    {{- include "afc-engine.selectorLabels" . | nindent 4 }}
    afc: psql
