apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: b-ssd
provisioner: filestore.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false
parameters:
  tier: standard
  network: "projects/shared-services-080817/global/networks/brcm-prod-shared"
  connect-mode: PRIVATE_SERVICE_ACCESS
