"""empty message

Revision ID: 0574ac12b90c
Revises: 878ecf2c3467
Create Date: 2023-11-08 16:52:43.406880

"""

# revision identifiers, used by Alembic.
revision = '0574ac12b90c'
down_revision = '878ecf2c3467'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('limit', sa.Numeric(precision=50), nullable=True))
    op.add_column('limits', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_constraint('limits_min_eirp_key', 'limits', type_='unique')
    op.create_unique_constraint('limits_name_unique', 'limits', ['name'])
    op.drop_column('limits', 'min_eirp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('limits', sa.Column('min_eirp', sa.NUMERIC(precision=50, scale=0), autoincrement=False, nullable=True))
    op.drop_constraint('limits_name_unique', 'limits', type_='unique')
    op.create_unique_constraint('limits_min_eirp_key', 'limits', ['min_eirp'])
    op.drop_column('limits', 'name')
    op.drop_column('limits', 'limit')
    # ### end Alembic commands ###
