"""empty message

Revision ID: 20bcbbdc61
Revises: 4435e833fee6
Create Date: 2022-11-08 23:12:44.204351

"""

# revision identifiers, used by Alembic.
revision = '20bcbbdc61'
down_revision = '4435e833fee6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_point', sa.Column('org', sa.String(length=64), nullable=True))
    connection = op.get_bind()
    connection.execute(
        "ALTER TABLE access_point DROP CONSTRAINT access_point_user_id_fkey")
    for ap in connection.execute('select id, user_id from access_point'):
        if ap[0]:
            if ap[1]:
                result = connection.execute('select org from aaa_user where id = %d limit 1' %ap[1])
                for org in result:
                    connection.execute(
                        "update access_point set org = '%s' where id = %d" % (org[0], ap[0]))
                    break
            else:
                connection.execute(
                        "update access_point set org = '' where id = %d" % (ap[0]))
        else:
            break

    op.drop_column('access_point', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_point', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'access_point_user_id_fkey', 'access_point', 'aaa_user', ['user_id'], ['id'], ondelete=u'CASCADE')
    op.drop_column('access_point', 'org')
    ### end Alembic commands ###
