"""oidc

Revision ID: 230b7680b81e
Revises: 4c904e86218d
Create Date: 2022-10-19 12:34:33.521092

"""

# revision identifiers, used by Alembic.
revision = '230b7680b81e'
down_revision = '4c904e86218d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    op.add_column('aaa_user', sa.Column('sub', sa.String(length=255), nullable=True))
    op.add_column('aaa_user', sa.Column('username', sa.String(length=50), nullable=True))
    connection = op.get_bind()
    for user in connection.execute('select id, email from aaa_user'):
        connection.execute(
            "update aaa_user set username = '%s' where id = %d" % (user[1], user[0]))
    connection.execute(
         "alter table aaa_user alter column username set not null")
    op.create_unique_constraint(None, 'aaa_user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'aaa_user', type_='unique')
    op.drop_column('aaa_user', 'username')
    op.drop_column('aaa_user', 'sub')
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('blacklisted_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'blacklist_tokens_pkey')
    )
    ### end Alembic commands ###
