"""empty message

Revision ID: 878ecf2c3467
Revises: c3d56c68042e
Create Date: 2023-05-30 21:37:53.543153

"""

# revision identifiers, used by Alembic.
revision = '878ecf2c3467'
down_revision = 'c3d56c68042e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_point_serial_number', table_name='access_point')
    op.drop_table('access_point')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_point',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('certification_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('org', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='access_point_pkey'),
    sa.UniqueConstraint('serial_number', name='access_point_serial_number_key')
    )
    op.create_index('ix_access_point_serial_number', 'access_point', ['serial_number'], unique=False)
    # ### end Alembic commands ###
