"""empty message

Revision ID: c3d56c68042e
Revises: 0b9577323e85
Create Date: 2023-04-25 19:23:52.811135

"""

# revision identifiers, used by Alembic.
revision = 'c3d56c68042e'
down_revision = '0b9577323e85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cert_id',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('certification_id', sa.String(length=64), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['aaa_ruleset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cert_id')
    # ### end Alembic commands ###
