#
# Copyright © 2022 Broadcom. All rights reserved. The term "Broadcom"
# refers solely to the Broadcom Inc. corporate affiliate that owns
# the software below. This work is licensed under the OpenAFC Project License,
# a copy of which is included with this software program
#
FROM centos:7 as staging
RUN groupadd -g 1003 fbrat
RUN useradd -u 1003 -g 1003 -m -b /var/lib -s /sbin/nologin fbrat
COPY prereqs /wd/prereqs/
RUN echo "ip_resolve=4" >> /etc/yum.conf
RUN yum -y upgrade

#this list is to be optimized in future
RUN yum install -y https://yum.puppetlabs.com/puppet7-release-el-7.noarch.rpm epel-release && \
	cd /wd/prereqs/repo/ && \
	yum install -y \
	rabbitmq-server \
	postfix \
	python2-flask-mail-0.9.1-2.el7.noarch.rpm \
	python2-flask-user-1.0.1.5-1.el7.noarch.rpm \
	python2-flask_jsonrpc-0.3.1-1.el7.noarch.rpm \
	python2-jsmin-2.2.2-2.el7.noarch.rpm \
	python-wsgidav-2.4.1-1.el7.noarch.rpm \
	rpmconf \
	boost169-thread \
	createrepo \
	puppet-agent \
	httpd \
	httpd-tools \
	mod_ssl \
	mailx \
	python2-celery \
	python-psycopg2 \
	awstats \
	python-requests

RUN yum -y upgrade

RUN cd /etc/pki/tls/certs && cp localhost.crt http.crt && cd /etc/pki/tls/private && cp localhost.key http.key
RUN yum -y clean all && yum -y fs

FROM centos:7
COPY --from=staging / /
LABEL version="openafc-centos-preinstall-image"
