apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
  labels:
    name: prometheus-server
  namespace: prometheus
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      evaluation_interval: 1m
      scrape_interval: 15s
      scrape_timeout: 5s
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    # Existing scrape configurations from your Helm chart config...

      # RMQ Service
      - job_name: 'rmq'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_afc]
            action: keep
            regex: rmq
          - action: replace
            target_label: __metrics_path__
            replacement: /metrics/detailed
          - source_labels: [__address__]
            action: replace
            target_label: __address__
            regex: (.*?)(?::\d+)?$
            replacement: $1:15692
        metrics_path: /metrics/detailed
        params:
          vhost: ['fbrat', 'rcache']
          family: ['queue_coarse_metrics']

      # Message Handler Service
      - job_name: 'msghnd'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_afc]
            action: keep
            regex: msghnd
          - action: replace
            target_label: __metrics_path__
            replacement: /fbrat/metrics
          - source_labels: [__address__]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: $1

      # ALS Siphon Service
      - job_name: 'als_siphon'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_afc]
            action: keep
            regex: als_siphon
          - source_labels: [__address__]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: $1:8080

      # Nginx Exporter Service
      - job_name: 'nginxexporter'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_afc]
            action: keep
            regex: nginxexporter
          - source_labels: [__address__]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: $1:9113

      # cAdvisor Service
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_afc]
            action: keep
            regex: cadvisor
          - source_labels: [__address__]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: $1:8080
        metric_relabel_configs:
          - source_labels: [name]
            regex: "(.*?)_(rat_server|als_siphon|uls_downloader|bulk_postgres|als_kafka|cert_db|rcache_tool|[^_]+)_[0-9]+"
            replacement: "$1"
            target_label: project
          - source_labels: [name]
            regex: "(.*?)_(rat_server|als_siphon|uls_downloader|bulk_postgres|als_kafka|cert_db|rcache_tool|[^_]+)_[0-9]+"
            replacement: "$2"
            target_label: service
          - regex: image
            action: labeldrop
          - regex: container_label_.*
            action: labeldrop

      - job_name: 'ingress-nginx'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['ingress-nginx']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "10254"  # Verify and use the actual metrics port of your ingress-nginx
          - action: replace
            source_labels: [__address__]
            target_label: __address__
            regex: (.+):(?:\d+)
            replacement: $1:10254  # Ensure this is the correct port for ingress-nginx metrics
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
        metrics_path: /metrics
          