apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}-webui-oidc-env
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}  # name of the SecretStore (or kind specified)
  target:
    name: {{ .Chart.Name }}-webui-oidc-env-secret            # name of the k8s Secret to be created
  data:
  - secretKey: oidc-env              # name of the GCPSM secret key
    remoteRef:
      key: oidc-env

