apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}-webui-rat-api
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}  # name of the SecretStore (or kind specified)
  target:
    name: {{ .Chart.Name }}-webui-rat-api-secret            # name of the k8s Secret to be created
  data:
  - secretKey: webui-rat-api              # name of the GCPSM secret key
    remoteRef:
      key: webui-rat-api

