apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: afc-int-ingress
  annotations:
    # Use annotations to configure specific ingress-nginx behaviors like SSL, timeouts, etc.
    networking.gke.io/load-balancer-type: "Internal"

    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # Add other necessary annotations based on your specific requirements.
spec:
  ingressClassName: nginx
  rules:
  #- host: {{ .Values.service.ingress_ngnix.hostname | quote }}
  - http:
      paths:
      - path: /fbrat/ap-afc/availableSpectrumInquirySec
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.webui.hostname | quote }}
            port:
              number: {{ .Values.service.webui.port }}
      - path: /fbrat/ap-afc/availableSpectrumInquiryInternal
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.msghnd.hostname | quote }}
            port:
              number: {{ .Values.service.msghnd.port }}
      - path: /fbrat/ap-afc/availableSpectrumInquiry
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.msghnd.hostname | quote }}
            port:
              number: {{ .Values.service.msghnd.port }}
      - path: /fbrat/ratapi/v1/files
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.webui.hostname | quote }}
            port:
              number: {{ .Values.service.webui.port }}
      - path: /fbrat/ratapi/v1/GetAfcConfigByRulesetID
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.msghnd.hostname | quote }}
            port:
              number: {{ .Values.service.msghnd.port }}
      - path: /fbrat/ratapi/v1/GetRulesetIDs
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.msghnd.hostname | quote }}
            port:
              number: {{ .Values.service.msghnd.port }}
      - path: /fbrat
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.webui.hostname | quote }}
            port:
              number: {{ .Values.service.webui.port }}
      - path: /certificate
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.objst.hostname | quote }}
            port:
              number: {{ .Values.service.objst.fileStoragePort }}
      # Add other paths as needed.
  # Add TLS configuration if you're using HTTPS.
#   tls:
#   - hosts:
#     - {{ .Values.service.ingress_ngnix.hostname | quote }}
#     secretName: your-tls-secret
