apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.rmq.hostname | quote }}
  labels:
    {{- include "afc-int.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rmq.type }}
  ports:
    - port: {{ .Values.service.rmq.port }}
      targetPort: rmqp
      protocol: TCP
      name: rmqp
  selector:
    {{- include "afc-int.selectorLabels" . | nindent 4 }}
    afc: rmq
