apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "afc-int.fullname" . }}-objst
  labels:
    {{- include "afc-int.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.objst }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "afc-int.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "afc-int.selectorLabels" . | nindent 8 }}
        afc: objst
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "afc-int.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image:  "{{ .Values.image.objst.repository }}:{{ .Values.image.objst.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.objst.pullPolicy }}
          ports:
            - name: afc-objst-port
              containerPort: {{ .Values.service.objst.fileStoragePort }}
              protocol: TCP
            - name: afc-objst-hist
              containerPort: {{ .Values.service.objst.historyViewPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: "/mnt/nfs"
              name: cont-confs
          env:
            # Filestorage params:
            - name: AFC_OBJST_PORT
              value: {{ .Values.service.objst.fileStoragePort | quote }}
            - name: AFC_OBJST_HIST_PORT
              value: {{ .Values.service.objst.historyViewPort | quote }}
            - name: AFC_OBJST_LOCAL_DIR
              value: "/mnt/nfs/storage"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cont-confs
          persistentVolumeClaim:
            claimName: cont-confs-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
