apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}-rabbitmq-dsn
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}  # name of the SecretStore (or kind specified)
  target:
    name: rabbitmq-consumer-secret        # name of the k8s Secret to be created
  data:
  - secretKey: rabbitmq-dsn               # name of the GCPSM secret key
    remoteRef:
      key: rabbitmq-dsn

