apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}-rcache-rmq-dsn
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}  # name of the SecretStore (or kind specified)
  target:
    name: rmq-rcache-secret               # name of the k8s Secret to be created
  data:
  - secretKey: rcache-rmq-dsn             # name of the GCPSM secret key
    remoteRef:
      key: rcache-rmq-dsn

