apiVersion: v1
kind: Service
metadata:
  name: {{ include "afc-int.fullname" . }}-rcache
  labels:
    {{- include "afc-int.labels" . | nindent 4 }}
spec:
  type:  {{ .Values.service.rcache.type }}
  ports:
    - name: rcache-port
      port: {{ .Values.service.rcache.port }}
      protocol: TCP
      targetPort: rcache-port
  selector:
    {{- include "afc-int.selectorLabels" . | nindent 4 }}
    afc: rcache
