apiVersion: v1
kind: Service
metadata:
  name: {{ include "afc-int.fullname" . }}-als-kafka
  labels:
    {{- include "afc-int.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.als_kafka.type }}
  ports:
    - name: als-kafka-port
      port: {{ .Values.service.als_kafka.port }}
      protocol: TCP
      targetPort: als-kafka-port
  selector:
    {{- include "afc-int.selectorLabels" . | nindent 4 }}
    afc: als-kafka
