apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.managed_service.nfs.storageClass.name | quote }}
provisioner: filestore.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false
parameters:
  tier: BASIC_SSD
  network: {{ .Values.managed_service.nfs.storageClass.network | quote }}
  connect-mode: PRIVATE_SERVICE_ACCESS
