# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# Deployment helmchart for als-siphon pods

{{- $ := mergeOverwrite $ (dict "component" "als-siphon") }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "afc.compManifestName" . }}
  labels: {{- include "afc.commonLabels" . | nindent 4 }}
  annotations: {{- include "afc.commonDeploymentAnnotations" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "afc.selectorLabels" . | nindent 6 }}
  replicas: {{ include "afc.replicas" . }}
  {{- include "afc.serviceAccountRef" . | indent 2 }}
  {{- include "afc.securityContext" . | indent 2 }}
  template:
    metadata:
      labels: {{- include "afc.commonLabels" . | nindent 8 }}
    spec:
      {{- include "afc.imagePullSecrets" . | indent 6 }}
      containers:
        - {{- include "afc.containerImage" . | nindent 10 }}
          {{- include "afc.probes" . | nindent 10 }}
          env: {{- include "afc.env" . | nindent 12 }}
          resources: {{- include "afc.containerResources" . | nindent 12 }}
          ports: {{- include "afc.containerPorts" . | nindent 12 }}
          volumeMounts: {{- include "afc.staticVolumeMounts" . | nindent 12 }}
      volumes:
        {{- include "afc.staticVolumes" . | nindent 8 }}
