# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# Postgres user password external secret
{{- $ := mergeOverwrite $ (dict "secret" "postgres-password") }}
{{- $extSecretDef := merge (dict) (default (dict) (get (default (dict) $.Values.externalSecrets) .secret)) (default (dict) (get (default (dict) $.Values.externalSecrets) "default")) -}}
{{- if hasKey $extSecretDef "property" }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "afc.secretManifestName" . }}
  labels: {{- include "afc.commonLabels" . | nindent 4 }}
spec:
  {{- include "afc.extSecretStoreRef" . | nindent 2 }}
  {{- include "afc.refreshInterval" $extSecretDef | indent 2 }}
  {{- include "afc.extSecretTarget" . | nindent 2 }}
  {{- include "afc.extSecretData" . | indent 2 }}

{{- end }}
