# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# Worker autoscaler on number of processed requests

{{- $ := mergeOverwrite $ (dict "component" "worker") }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "afc.compManifestName" . }}
  labels: {{- include "afc.commonLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "afc.compManifestName" . }}
  {{- include "afc.hpaReplicas" . | nindent 2 }}
  {{- include "afc.hpaBehavior" . | nindent 2 }}
  metrics: {{- include "afc.hpaMetric" . | nindent 4 }}
