# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# helm/afc-int/values.yaml overrides for external GCP cluster

components:
  dispatcher:
    service:
      annotations:
        networking.gke.io/internal-load-balancer-allow-global-access: "true"
        networking.gke.io/load-balancer-type: Internal