# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# This values.yaml override, common to external and internal AFC clusters is
# used by:
#  - start.py:
#     - As --values parameter to helm_install_int/ext.py
#     - As --ext_cfg parameter to install_prerequisites (as it contains
#       IP addresses that might be useful there)
#     - For printing IP addresses at the end
#  - repository_push.py
#     - For push/pull image repository addresses

# Static IPs of internal and external clusters
# This dictionary is used by AFC helmcharts of both clusters and by
# install_prerequisites.py
externalIps:
  # Ingress of internal cluster
  int-ingress: 10.255.144.213
  # RabbitMQ AMQP of internal cluster
  int-rmq: 10.255.144.214
  # Dispatcher on external cluster
  ext-dispatcher: 10.255.16.24
  # Postgres server
  postgres: 10.255.169.3

imageRepositories:
  public:
    path: wcc-afc-docker-virtual.usw2.packages.broadcom.com
    pushPath: wcc-afc-docker-dev-local.usw2.packages.broadcom.com
    pullSecrets:
      - image-pull
  private:
    path: wcc-afc-docker-virtual.usw2.packages.broadcom.com
    pushPath: wcc-afc-docker-dev-local.usw2.packages.broadcom.com
    pullSecrets:
      - image-pull

secretStores:
  secret-store:
    provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
        projectID: wcc-enterprise-afc-stg
