#
# Copyright © 2021 Broadcom. All rights reserved. The term "Broadcom"
# refers solely to the Broadcom Inc. corporate affiliate that owns
# the software below. This work is licensed under the OpenAFC Project License,
# a copy of which is included with this software program
#
# default value of args
ARG BLD_TAG=3.8.7.0
ARG PRINST_TAG=3.8.7.0
ARG BLD_NAME=public.ecr.aws/w9v6y1o0/openafc/worker-al-build-image
ARG PRINST_NAME=public.ecr.aws/w9v6y1o0/openafc/worker-al-preinstall

# Stage Build
FROM ${BLD_NAME}:${BLD_TAG} as build_image
ARG BUILDREV=localbuild
COPY CMakeLists.txt LICENSE.txt version.txt Doxyfile.in /root/afc/
COPY cmake /root/afc/cmake/
COPY pkg /root/afc/pkg/
COPY selinux /root/afc/selinux/
COPY src /root/afc/src/

RUN apk add py3-setuptools

RUN mkdir -p -m 777 /root/afc/build
RUN cd /root/afc/build && \
cmake -DCMAKE_INSTALL_PREFIX=/root/afc/__install -DCMAKE_BUILD_TYPE=Ulsprocessor -DSVN_LAST_REVISION=$BUILDREV -G Ninja /root/afc && \
ninja -j$(nproc --all --ignore=2) install

FROM ${PRINST_NAME}:${PRINST_TAG} as install_image
RUN mkdir -p /mnt/nfs/rat_transfer/daily_uls_parse/data_files \
            /mnt/nfs/rat_transfer/daily_uls_parse/temp \
            /mnt/nfs/rat_transfer/ULS_Database \
            /mnt/nfs/rat_transfer/Antenna_Patterns \
            /output_folder

COPY --from=build_image /root/afc/__install/bin /mnt/nfs/rat_transfer/daily_uls_parse/
COPY --from=build_image /root/afc/build/src/ratapi/pkg/ratapi/db/ /mnt/nfs/rat_transfer/daily_uls_parse/
RUN apk add py3-sqlalchemy py3-numpy
COPY uls/uls-docker-entrypoint.sh /wd/
RUN chmod +x /wd/uls-docker-entrypoint.sh

FROM alpine:3.17
COPY --from=install_image / /

WORKDIR /wd
ENV AFC_DEVEL_ENV=${AFC_DEVEL_ENV:-production}
CMD ["./uls-docker-entrypoint.sh"]
