# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# Grafana admin password
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
stringData:
    GRAFANA_ADMIN_PASSWORD: admin
