# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# Postgres password for read-only access to JSON log database
apiVersion: v1
kind: Secret
metadata:
    name: als-json-log-ro-db-password
stringData:
    ALS_JSON_LOG_RO_DB_PASSWORD: postgres
