# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# OIDC_CLIENT_ID OIDCConfigurator Flask config setting
apiVersion: v1
kind: Secret
metadata:
    name: oidc-client-id
stringData:
    OIDC_CLIENT_ID: >-
        0oa1l4upqt6ddSjZ01d8
