# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# OIDC_CLIENT_SECRET OIDCConfigurator Flask config setting
apiVersion: v1
kind: Secret
metadata:
    name: oidc-client-secret
stringData:
    OIDC_CLIENT_SECRET: >-
        IM-zW3EgaWQ7aSZQ8Wdhs1Om1zZ0io4xmdE3uisj
