# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# CAPTCHA_SITEKEY RatapiConfigurator Flask config setting
apiVersion: v1
kind: Secret
metadata:
    name: ratapi-captcha-sitekey
stringData:
    CAPTCHA_SITEKEY: >-
        6LefcywlAAAAABvv2ReianjjX3xWh1yfaahdb9wF
