# Copyright (C) 2022 Broadcom. All rights reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate
# that owns the software below.
# This work is licensed under the OpenAFC Project License, a copy of which is
# included with this software program.

# Password for DB creator user on ratdb server
apiVersion: v1
kind: Secret
metadata:
    name: db-creator-password-ratdb
stringData:
    DB_CREATOR_PASSWORD_RATDB: postgres
